---
abstract: 'Tiny C Compiler for FFI'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Alien::TinyCC: '0'
  Archive::Ar: '2.02'
  File::chdir: '0'
  IPC::System::Simple: '0'
  Module::Build: '0.3601'
  Path::Class: '0.26'
  Test::More: '0.94'
  autodie: '0'
  perl: '5.010'
configure_requires:
  Alien::TinyCC: '0'
  Archive::Ar: '2.02'
  File::chdir: '0'
  IPC::System::Simple: '0'
  Module::Build: '0.3601'
  Path::Class: '0'
  autodie: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FFI-TinyCC
requires:
  Carp: '0'
  FFI::Raw: '0.32'
  File::ShareDir: '0'
  base: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/plicease/FFI-TinyCC/issues
  homepage: http://perl.wdlabs.com/FFI-TinyCC
  repository: git://github.com/plicease/FFI-TinyCC.git
version: '0.07'
